# Generated by Django 6.0.1 on 2026-01-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='TEMP001', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
